name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  github-release:
    name: Publish GitHub release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      CHGLOG_VERSION: "0.15.4"

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Check SmartWatts package version
      shell: python
      env:
        PYTHONPATH: ${{ github.workspace }}/src
      run: |
        import os
        import sys
        from smartwatts import __version__

        git_tag = os.environ['GITHUB_REF_NAME'].removeprefix('v')
        pkg_version = __version__

        if git_tag != pkg_version:
          title = 'Invalid version'
          file = 'smartwatts/__init__.py'
          msg = f'Version mismatch between python package ({pkg_version}) and git tag ({git_tag})'
          print(f'::error title={title},file={file}::{msg}')
          sys.exit(1)

    - name: Generate version changelog
      run: |
        set -euo pipefail
        export BASE_URL="https://github.com/git-chglog/git-chglog/releases/download"
        export FILENAME="git-chglog_${CHGLOG_VERSION}_linux_amd64.tar.gz"
        curl -fsSL "${BASE_URL}/v${CHGLOG_VERSION}/${FILENAME}" |sudo tar xz --no-same-owner -C /usr/local/bin git-chglog
        git-chglog --config .github/chglog/config.yml --output CHANGELOG.md "${GITHUB_REF_NAME}"

    - name: Create GitHub release
      uses: softprops/action-gh-release@a74c6b72af54cfa997e81df42d94703d6313a2d0 # v2.0.6
      with:
        body_path: CHANGELOG.md

  pypi-package:
    name: Publish Pypi package
    runs-on: ubuntu-latest
    needs: github-release
    permissions:
      contents: read
      id-token: write

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.x"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build

    - name: Build package
      run: python -m build

    - name: Publish package
      uses: pypa/gh-action-pypi-publish@ec4db0b4ddc65acdf4bff5fa45ac92d78b56bdf0 # v1.9.0
      with:
        print-hash: true

  docker-image:
    name: Publish Docker image
    runs-on: ubuntu-latest
    needs: github-release
    permissions:
      contents: read
      packages: write

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@68827325e0b33c7199eb31dd4e31fbe9023e06e3 # v3.0.0

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@d70bba72b1f3fd22344832f00baa16ece964efeb # v3.3.0

      - name: Log in to Docker Hub
        uses: docker/login-action@0d4c9c5ea7693da7b068278f7b52bda2a190a446 # v3.2.0
        with:
          username: ${{ vars.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@0d4c9c5ea7693da7b068278f7b52bda2a190a446 # v3.2.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@8e5442c4ef9f78752691e2d8f8d19755c6f78e81 # v5.5.1
        with:
          images: |
            docker.io/powerapi/smartwatts-formula
            ghcr.io/powerapi-ng/smartwatts-formula
          tags: |
            type=pep440,pattern={{version}}

      - name: Build and push Docker image
        uses: docker/build-push-action@15560696de535e4014efeff63c48f16952e52dd1 # v6.2.0
        id: build-and-push
        with:
          push: true
          provenance: false
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
